import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#16181d',
    },
    topBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingBottom: 16,
        backgroundColor: '#1a1c23',
        borderBottomWidth: 1,
        borderBottomColor: '#26282f',
    },
    topBarLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    avatarTop: {
        width: 32,
        height: 32,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#334155',
    },
    topBarTitle: {
        color: '#e11d48',
        fontSize: 16,
        fontWeight: '900',
        letterSpacing: 1,
    },
    topBarRight: {
        flexDirection: 'row',
        gap: 16,
        alignItems: 'center',
    },
    iconBtn: {
        padding: 4,
    },
    scrollContent: {
        padding: 24,
    },
    subtitle: {
        fontSize: 10,
        color: '#fca5a5',
        letterSpacing: 2,
        textTransform: 'uppercase',
        fontWeight: '700',
        marginBottom: 4,
    },
    mainTitle: {
        fontSize: 32,
        fontWeight: '900',
        color: '#f8fafc',
        letterSpacing: -1,
        lineHeight: 34,
        marginBottom: 12,
    },
    descText: {
        fontSize: 12,
        color: '#94a3b8',
        lineHeight: 18,
        marginBottom: 24,
    },
    actionBtn: {
        backgroundColor: '#dc2626',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        borderRadius: 6,
        gap: 8,
        marginBottom: 32,
    },
    actionBtnText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: '800',
        letterSpacing: 1,
    },
    vehicleCard: {
        backgroundColor: '#1b1d24',
        borderRadius: 8,
        marginBottom: 16,
        overflow: 'hidden',
        position: 'relative',
    },
    vehicleLeftBorder: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: 4,
        backgroundColor: '#dc2626',
        zIndex: 10,
    },
    vehicleImg: {
        width: '100%',
        height: 140,
        opacity: 0.8,
    },
    vehicleInfo: {
        padding: 20,
    },
    vehicleTitleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
    },
    vehicleName: {
        color: '#f8fafc',
        fontSize: 18,
        fontWeight: '900',
    },
    statusBadge: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    statusTextWhite: {
        color: '#fff',
        fontSize: 9,
        fontWeight: '900',
        letterSpacing: 0.5,
    },
    vehicleType: {
        color: '#f8fafc',
        fontSize: 9,
        fontWeight: '700',
        letterSpacing: 1,
        marginBottom: 20,
    },
    statsRow: {
        flexDirection: 'row',
        gap: 16,
        marginBottom: 20,
    },
    statBox: {
        flex: 1,
    },
    statLabel: {
        color: '#f8fafc',
        fontSize: 8,
        fontWeight: '800',
        letterSpacing: 1,
        marginBottom: 6,
    },
    barBg: {
        height: 4,
        backgroundColor: '#334155',
        borderRadius: 2,
        marginBottom: 4,
    },
    barBgRed: {
        height: 4,
        backgroundColor: '#334155',
        borderRadius: 2,
        marginTop: 12,
    },
    barFill: {
        height: '100%',
        borderRadius: 2,
    },
    statValue: {
        color: '#f8fafc',
        fontSize: 10,
        fontWeight: '800',
        textAlign: 'right',
    },
    vehicleActions: {
        flexDirection: 'row',
        gap: 12,
    },
    vehicleBtn: {
        flex: 1,
        backgroundColor: '#26282f',
        paddingVertical: 10,
        alignItems: 'center',
        borderRadius: 4,
    },
    vehicleBtnText: {
        color: '#cbd5e1',
        fontSize: 10,
        fontWeight: '800',
        letterSpacing: 1,
    },
    warningRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 20,
    },
    warningText: {
        color: '#fca5a5',
        fontSize: 11,
    },
    fullWidthBtn: {
        backgroundColor: '#26282f',
        paddingVertical: 12,
        alignItems: 'center',
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#334155',
    },
    fullWidthBtnText: {
        color: '#cbd5e1',
        fontSize: 10,
        fontWeight: '800',
        letterSpacing: 1,
    },
    sectionTitle: {
        color: '#f8fafc',
        fontSize: 16,
        fontWeight: '900',
        letterSpacing: 1,
        marginTop: 16,
        marginBottom: 16,
    },
    toolCard: {
        backgroundColor: '#1b1d24',
        borderRadius: 8,
        padding: 20,
        marginBottom: 12,
    },
    toolHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    toolIconBox: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#1e3a8a',
        alignItems: 'center',
        justifyContent: 'center',
    },
    toolIconBoxRed: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#451a1a',
        alignItems: 'center',
        justifyContent: 'center',
    },
    toolBadge: {
        backgroundColor: '#1e3a8a',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    toolBadgeText: {
        color: '#93c5fd',
        fontSize: 8,
        fontWeight: '800',
        letterSpacing: 0.5,
    },
    toolBadgeRed: {
        backgroundColor: '#451a1a',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    toolBadgeTextRed: {
        color: '#fca5a5',
        fontSize: 8,
        fontWeight: '800',
        letterSpacing: 0.5,
    },
    toolBadgeDark: {
        backgroundColor: '#334155',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    toolBadgeTextWhite: {
        color: '#f8fafc',
        fontSize: 8,
        fontWeight: '800',
        letterSpacing: 0.5,
    },
    toolName: {
        color: '#f8fafc',
        fontSize: 15,
        fontWeight: '800',
        marginBottom: 4,
    },
    toolDesc: {
        color: '#f8fafc',
        fontSize: 11,
    },
    toolFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 16,
    },
    dotsRow: {
        flexDirection: 'row',
        gap: 4,
    },
    dot: {
        width: 12,
        height: 12,
        borderRadius: 6,
    },
    toolStatusText: {
        color: '#f8fafc',
        fontSize: 9,
        fontWeight: '800',
        letterSpacing: 1,
    },
    toolStatusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 16,
    },
    dotSmall: {
        width: 6,
        height: 6,
        borderRadius: 3,
    },
    toolStatusTextWhite: {
        color: '#f8fafc',
        fontSize: 9,
        fontWeight: '800',
        letterSpacing: 1,
    },
    warningTextSmall: {
        color: '#fca5a5',
        fontSize: 9,
        fontWeight: '800',
        letterSpacing: 1,
        marginTop: 16,
    },
    tabRow: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 24,
    },
    tab: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        paddingVertical: 12,
        borderRadius: 6,
        backgroundColor: '#26282f',
    },
    tabActive: {
        backgroundColor: '#dc2626',
    },
    tabText: {
        color: '#64748b',
        fontSize: 10,
        fontWeight: '800',
        letterSpacing: 1,
    },
    tabTextActive: {
        color: '#fff',
    },
    baseHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 16,
    },
    baseHeaderText: {
        color: '#93c5fd',
        fontSize: 12,
        fontWeight: '800',
        letterSpacing: 1,
    },
    modalCenteredView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(15, 23, 42, 0.85)',
        padding: 20,
    },
    modalView: {
        width: '100%',
        maxWidth: 400,
        backgroundColor: '#1b1d24',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#26282f',
        padding: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 8,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 16,
    },
    modalTitle: {
        color: '#f8fafc',
        fontSize: 18,
        fontWeight: '900',
        letterSpacing: 1,
    },
    modalDesc: {
        color: '#94a3b8',
        fontSize: 12,
        lineHeight: 18,
        marginBottom: 20,
    },
    modalInput: {
        backgroundColor: '#16181d',
        borderColor: '#334155',
        borderWidth: 1,
        borderRadius: 6,
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginBottom: 24,
    },
    modalActions: {
        flexDirection: 'row',
        gap: 12,
    },
    modalBtn: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 6,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalBtnCancel: {
        backgroundColor: '#26282f',
    },
    modalBtnConfirm: {
        backgroundColor: '#e11d48',
    },
    modalBtnTextCancel: {
        color: '#cbd5e1',
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1,
    },
    modalBtnTextConfirm: {
        color: '#fff',
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1,
    },
});