import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#0a0f12', padding: 20 },
    confirmScroll: { flexGrow: 1, paddingBottom: 40 },
    centeredFlex: { flex: 1, alignItems: 'center', justifyContent: 'center' },

    header: { alignItems: 'center', marginBottom: 20, width: '100%' },
    headerTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', width: '100%', position: 'relative' },
    refreshIcon: { position: 'absolute', right: 0, padding: 10 },

    time: { fontSize: 48, color: '#fff', fontWeight: 'bold' },
    date: { color: '#90a4ae', fontSize: 12, letterSpacing: 2 },
    alertBox: { flexDirection: 'row', gap: 10, backgroundColor: '#dc2626', padding: 16, borderRadius: 12, marginBottom: 20, alignItems: 'center' },
    alertTitle: { color: '#fff', fontWeight: 'bold' },
    alertSubtitle: { color: '#fecaca', fontSize: 12 },
    card: { backgroundColor: 'rgba(17,24,39,0.7)', padding: 20, borderRadius: 16, marginBottom: 20 },
    label: { color: '#90a4ae', fontSize: 10, marginBottom: 4 },
    text: { color: '#fff', marginBottom: 4 },
    critical: { color: '#ef4444', fontWeight: 'bold' },
    row: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 10 },
    location: { flexDirection: 'row', gap: 8, marginTop: 10 },
    locationText: { color: '#cfd8dc', flex: 1 },
    errorBox: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: 'rgba(239,68,68,0.15)', borderWidth: 1, borderColor: '#ef4444', borderRadius: 8, padding: 12, marginBottom: 12 },
    errorText: { color: '#ef4444', fontSize: 13, flex: 1 },

    actions: { marginTop: 30, gap: 10, paddingBottom: 20 },
    confirmButton: { backgroundColor: '#dc2626', padding: 16, borderRadius: 12, flexDirection: 'row', justifyContent: 'center', gap: 10 },
    rejectButton: { backgroundColor: '#1f2937', padding: 16, borderRadius: 12, flexDirection: 'row', justifyContent: 'center', gap: 10 },
    buttonDisabled: { opacity: 0.6 },
    buttonText: { color: '#fff', fontWeight: 'bold' },
    footer: { textAlign: 'center', color: '#455a64', marginTop: 20, fontSize: 10 },

    // ── Pantalla de Confirmación y Estados de Tarjeta ───────────────────────────
    confirmationCard: { width: '100%', borderRadius: 24, padding: 32, alignItems: 'center', gap: 10, borderWidth: 1, marginBottom: 20 },
    confirmationCardAccepted: { backgroundColor: 'rgba(34,197,94,0.1)', borderColor: 'rgba(34,197,94,0.3)' },
    confirmationCardRejected: { backgroundColor: 'rgba(239,68,68,0.1)', borderColor: 'rgba(239,68,68,0.3)' },
    confirmationCardFinalized: { backgroundColor: '#1e293b', borderColor: '#334155' },
    confirmationTitle: { color: '#fff', fontSize: 20, fontWeight: 'bold', textAlign: 'center', marginTop: 6 },
    confirmationSubtitle: { color: '#90a4ae', fontSize: 13, textAlign: 'center', lineHeight: 20 },
    confirmationBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(255,255,255,0.05)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, marginTop: 6 },
    confirmationTime: { color: '#90a4ae', fontSize: 12 },
    changeButton: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 12, paddingHorizontal: 20, borderRadius: 10, borderWidth: 1, borderColor: 'rgba(144,164,174,0.3)', alignSelf: 'center', marginTop: 8 },
    changeButtonText: { color: '#90a4ae', fontSize: 14 },

    // ── AX-14: Card de Tiempos Críticos ────────────────────────────────────────
    tiemposCard: {
        backgroundColor: 'rgba(17,24,39,0.85)',
        borderRadius: 16, padding: 20, marginBottom: 16,
        borderWidth: 1, borderColor: 'rgba(220,38,38,0.2)',
    },
    tiemposHeader: {
        flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6,
    },
    tiemposTitulo: {
        color: '#dc2626', fontSize: 11, fontWeight: '900', letterSpacing: 1.2,
    },
    tiemposDesc: {
        color: '#475569', fontSize: 11, fontWeight: '500',
        marginBottom: 20, lineHeight: 16,
    },
    botonGuardarTiempos: {
        flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
        gap: 8, backgroundColor: '#dc2626',
        borderRadius: 10, paddingVertical: 14, marginTop: 4,
    },
    botonGuardarTiemposTexto: {
        color: '#fff', fontSize: 12, fontWeight: '900', letterSpacing: 1,
    },
    // Responders List
    respondersPreview: {
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.2)',
    },
    respondersHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 12,
    },
    respondersTitle: {
        color: '#3b82f6',
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 1,
    },
    respondersGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    responderChip: {
        backgroundColor: 'rgba(255,255,255,0.05)',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 6,
    },
    responderChipText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: '700',
    },
    respondersSmallList: {
        marginTop: 20,
        width: '100%',
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.1)',
    },
    respondersSmallTitle: {
        color: '#fff',
        fontSize: 10,
        fontWeight: '900',
        marginBottom: 8,
        textAlign: 'center',
    },
    responderRowMini: {
        color: '#cfd8dc',
        fontSize: 11,
        flex: 1,
    },
    responderMoreText: {
        color: '#3b82f6',
        fontSize: 11,
        fontWeight: 'bold',
        textAlign: 'center',
        marginTop: 4,
    },
    // Resumen de respuestas en confirmación
    respondersSummaryBox: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        paddingVertical: 12,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        marginVertical: 16,
    },
    summaryItem: {
        alignItems: 'center',
        paddingHorizontal: 12,
    },
    summaryNum: {
        fontSize: 20,
        fontWeight: '900',
    },
    summaryLabel: {
        fontSize: 9,
        color: '#90a4ae',
        fontWeight: '700',
        marginTop: 2,
    },
    summaryDivider: {
        width: 1,
        height: 20,
        backgroundColor: 'rgba(255,255,255,0.1)',
    },
    miniRespondersScroll: {
        width: '100%',
        marginTop: 8,
        gap: 4,
    },
    miniResponderItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: 'rgba(255,255,255,0.03)',
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 8,
    },
    boardAccessButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
        backgroundColor: '#0284c7',
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 12,
        marginTop: 14,
        width: '100%',
        shadowColor: '#0284c7',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 5,
        borderWidth: 1,
        borderColor: 'rgba(2, 132, 199, 0.5)'
    },
    boardAccessButtonText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '900',
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 24,
        marginTop: 40,
    },
    pulseContainer: {
        position: 'relative',
        width: 120,
        height: 120,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 28,
    },
    pulseRing: {
        position: 'absolute',
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: 'rgba(16, 185, 129, 0.08)',
        borderWidth: 1.5,
        borderColor: 'rgba(16, 185, 129, 0.2)',
    },
    pulseIconContainer: {
        width: 90,
        height: 90,
        borderRadius: 45,
        backgroundColor: 'rgba(16, 185, 129, 0.15)',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(16, 185, 129, 0.3)',
    },
    emptyTitle: {
        color: '#fff',
        fontSize: 20,
        fontWeight: '900',
        letterSpacing: 1,
        marginBottom: 8,
        textAlign: 'center',
    },
    emptySubtitle: {
        color: '#90a4ae',
        fontSize: 13,
        textAlign: 'center',
        lineHeight: 20,
        paddingHorizontal: 20,
        marginBottom: 24,
    },
    statusBoxActive: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(16, 185, 129, 0.05)',
        borderWidth: 1,
        borderColor: 'rgba(16, 185, 129, 0.2)',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 30,
        marginBottom: 32,
    },
    greenDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#10b981',
        marginRight: 10,
    },
    statusBoxText: {
        color: '#10b981',
        fontSize: 10,
        fontWeight: '900',
        letterSpacing: 1,
    },
    emptyRefreshButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: '#1f2937',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#374151',
    },
    emptyRefreshButtonText: {
        color: '#94a3b8',
        fontSize: 12,
        fontWeight: '800',
        letterSpacing: 0.5,
    },
});