import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#16181d',
    },
    topBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingBottom: 16,
        backgroundColor: '#1a1c23',
        borderBottomWidth: 1,
        borderBottomColor: '#26282f',
    },
    topBarLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    backButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#334155',
        alignItems: 'center',
        justifyContent: 'center',
    },
    topBarTitle: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '900',
        letterSpacing: 1,
    },
    scrollContent: {
        padding: 20,
    },
    formContainer: {
        backgroundColor: '#1b1d24',
        padding: 20,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#26282f',
    },
    inputGroup: {
        marginBottom: 20,
    },
    label: {
        color: '#e2e8f0',
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1,
        marginBottom: 8,
        textTransform: 'uppercase',
    },
    dropdownWrapper: {
        backgroundColor: '#26282f',
        borderRadius: 8,
        height: 48,
        paddingHorizontal: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: '#334155',
    },
    dropdownValue: {
        color: '#e2e8f0',
        fontSize: 13,
        fontWeight: '600',
    },
    pickerContainer: {
        backgroundColor: '#26282f',
        borderRadius: 8,
        marginTop: 4,
        marginBottom: 16,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#334155',
    },
    pickerOption: {
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#1b1d24',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    pickerOptionText: {
        color: '#e2e8f0',
        fontSize: 13,
        fontWeight: '600',
    },
    fluidSection: {
        marginBottom: 24,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#26282f',
    },
    fluidLabel: {
        color: '#f8fafc',
        fontSize: 12,
        fontWeight: '800',
        marginBottom: 10,
        letterSpacing: 0.5,
    },
    statusRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 8,
    },
    statusButton: {
        flex: 1,
        height: 40,
        borderRadius: 6,
        backgroundColor: '#26282f',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#334155',
    },
    statusButtonText: {
        fontSize: 10,
        fontWeight: '950',
        color: '#94a3b8',
        letterSpacing: 0.5,
    },
    // Active states
    statusOkActive: {
        backgroundColor: 'rgba(16, 185, 129, 0.15)',
        borderColor: '#10b981',
    },
    statusOkActiveText: {
        color: '#10b981',
    },
    statusBajoActive: {
        backgroundColor: 'rgba(245, 158, 11, 0.15)',
        borderColor: '#f59e0b',
    },
    statusBajoActiveText: {
        color: '#f59e0b',
    },
    statusCriticoActive: {
        backgroundColor: 'rgba(239, 68, 68, 0.15)',
        borderColor: '#ef4444',
    },
    statusCriticoActiveText: {
        color: '#ef4444',
    },
    inputWrapperMultiline: {
        backgroundColor: '#26282f',
        borderRadius: 8,
        height: 100,
        paddingHorizontal: 14,
        paddingTop: 12,
        borderWidth: 1,
        borderColor: '#334155',
    },
    inputMultiline: {
        color: '#e2e8f0',
        fontSize: 13,
        height: '100%',
        textAlignVertical: 'top',
    },
    submitButton: {
        borderRadius: 8,
        height: 54,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
        marginTop: 16,
        overflow: 'hidden',
    },
    gradientButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
        height: '100%',
    },
    submitButtonText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '900',
        letterSpacing: 0.8,
    },
});
