import { StyleSheet, Platform } from 'react-native';
import { Colors, Spacing, Radius } from '../theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#242f3e',
    },

    // ── Markers nativos ─────────────────────────────────────────────────────────
    stationMarker: {
        width: 14,
        height: 14,
        borderRadius: 7,
        backgroundColor: '#263238',
        borderWidth: 2.5,
        borderColor: '#dc2626',
        ...Platform.select({
            ios: { shadowColor: '#dc2626', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.65, shadowRadius: 4 },
            android: { elevation: 6 },
        }),
    },
    poiMarker: {
        width: 28,
        height: 28,
        borderRadius: 14,
        borderWidth: 2,
        borderColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        ...Platform.select({
            ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 3 },
            android: { elevation: 4 },
        }),
    },
    incidentMarkerContainer: {
        width: 52,
        height: 52,
        alignItems: 'center',
        justifyContent: 'center',
    },
    incidentPulseRing: {
        position: 'absolute',
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(220,38,38,0.4)',
    },
    incidentPin: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: '#dc2626',
        borderWidth: 3,
        borderColor: '#7f1d1d',
        alignItems: 'center',
        justifyContent: 'center',
        ...Platform.select({
            ios: { shadowColor: '#dc2626', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.7, shadowRadius: 8 },
            android: { elevation: 8 },
        }),
    },

    // ── Callout ─────────────────────────────────────────────────────────────────
    calloutBox: {
        minWidth: 120,
        maxWidth: 250,
        padding: 4,
    },
    calloutTitle: {
        fontWeight: '800',
        fontSize: 13,
        color: '#1a1c23',
    },
    calloutDesc: {
        fontSize: 11,
        color: '#64748b',
        marginTop: 2,
    },

    // ── Header ──────────────────────────────────────────────────────────────────
    topOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        paddingHorizontal: Spacing.lg,
        zIndex: 10,
    },
    headerBar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: Spacing.sm,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    avatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255,255,255,0.92)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        fontSize: 16,
        fontWeight: '900',
        letterSpacing: -0.5,
        color: '#fff',
        textTransform: 'uppercase',
        ...Platform.select({
            ios: {},
            android: {},
            web: { textShadow: '0px 1px 4px rgba(0,0,0,0.3)' },
        }),
    },
    emergencyIcon: {
        width: 36,
        height: 36,
        borderRadius: Radius.lg,
        backgroundColor: 'rgba(255,255,255,0.92)',
        alignItems: 'center',
        justifyContent: 'center',
    },

    // ── Mission card ────────────────────────────────────────────────────────────
    missionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(38,50,56,0.9)',
        borderRadius: Radius.xxl,
        paddingVertical: Spacing.md,
        paddingHorizontal: Spacing.lg,
    },
    missionLeft: { flex: 1 },
    missionLabel: {
        fontSize: 8,
        fontWeight: '800',
        color: 'rgba(255,255,255,0.55)',
        letterSpacing: 1.2,
        textTransform: 'uppercase',
        marginBottom: 3,
    },
    missionStatusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
    },
    statusDotRed: {
        width: 7,
        height: 7,
        borderRadius: 4,
        backgroundColor: Colors.primary,
    },
    missionStatus: {
        fontSize: 11,
        fontWeight: '800',
        color: '#fff',
        letterSpacing: 0.2,
        lineHeight: 14,
    },
    missionLocation: {
        fontSize: 9,
        color: '#94a3b8',
        marginTop: 1,
    },
    missionDivider: {
        width: 1,
        height: 32,
        backgroundColor: 'rgba(255,255,255,0.15)',
        marginHorizontal: Spacing.sm,
    },
    missionRightContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    missionRight: { alignItems: 'flex-start' },
    respondersCount: {
        fontSize: 12,
        fontWeight: '900',
        color: '#fff',
        letterSpacing: 0.2,
    },
    respondersStatus: {
        fontSize: 9,
        fontWeight: '700',
        color: 'rgba(255,255,255,0.55)',
        letterSpacing: 0.5,
    },
    avatarStack: {
        flexDirection: 'row',
        marginLeft: Spacing.sm,
    },
    miniAvatar: {
        width: 24,
        height: 24,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: 'rgba(38,50,56,0.9)',
    },
    avatarCount: {
        fontSize: 8,
        fontWeight: '800',
        color: '#fff',
    },

    // ── Controles del mapa ──────────────────────────────────────────────────────
    mapControls: {
        position: 'absolute',
        right: Spacing.lg,
        gap: 1,
        backgroundColor: 'rgba(255,255,255,0.92)',
        borderRadius: Radius.lg,
        overflow: 'hidden',
    },
    controlBtn: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    floatingMapFab: {
        position: 'absolute',
        bottom: 120,
        left: Spacing.lg,
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#dc2626',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#7f1d1d',
        ...Platform.select({
            ios: {
                shadowColor: '#dc2626',
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.5,
                shadowRadius: 8,
            },
            android: { elevation: 8 },
            web: { boxShadow: '0px 4px 12px rgba(220, 38, 38, 0.5)' },
        }),
    },

    // ── F3: Panel de capas ──────────────────────────────────────────────────────
    panelCapas: {
        position: 'absolute',
        right: Spacing.lg + 48,
        backgroundColor: '#1a1c23',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#1f2937',
        overflow: 'hidden',
        minWidth: 155,
        zIndex: 20,
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.4,
                shadowRadius: 8,
            },
            android: { elevation: 10 },
        }),
    },
    panelCapasTitulo: {
        color: '#64748b',
        fontSize: 8,
        fontWeight: '800',
        letterSpacing: 1.2,
        paddingHorizontal: 12,
        paddingTop: 10,
        paddingBottom: 6,
        textTransform: 'uppercase',
    },
    filaToggle: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderLeftWidth: 3,
        borderLeftColor: '#1f2937',
        borderBottomWidth: 1,
        borderBottomColor: '#1f2937',
    },
    filaToggleTexto: {
        flex: 1,
        color: '#e2e8f0',
        fontSize: 11,
        fontWeight: '600',
    },
    filaToggleTextoInactivo: {
        color: '#475569',
    },
    toggleDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#1f2937',
    },

    // ── F1: Banner alertas ──────────────────────────────────────────────────────
    bannerAlertas: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: '#dc2626',
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingVertical: 9,
        marginBottom: 8,
        zIndex: 20,
        ...Platform.select({
            ios: {
                shadowColor: '#dc2626',
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.45,
                shadowRadius: 8,
            },
            android: { elevation: 8 },
        }),
    },
    puntoPulso: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#fff',
    },
    bannerTexto: {
        color: '#fff',
        fontSize: 12,
        fontWeight: '700',
    },

    // ── F1: Loading overlay ─────────────────────────────────────────────────────
    overlayLoading: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: '#0a0f12',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        zIndex: 50,
    },
    overlayTitulo: {
        color: '#fff',
        fontSize: 17,
        fontWeight: '700',
        marginTop: 4,
    },
    overlaySubtitulo: {
        color: '#64748b',
        fontSize: 12,
        textAlign: 'center',
        paddingHorizontal: 32,
    },

    // ── F1: Error banner ────────────────────────────────────────────────────────
    bannerError: {
        position: 'absolute',
        left: 16,
        right: 16,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: 'rgba(127,0,0,0.88)',
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 7,
        borderWidth: 1,
        borderColor: 'rgba(220,38,38,0.4)',
        zIndex: 20,
    },
    bannerErrorTexto: {
        flex: 1,
        color: '#fca5a5',
        fontSize: 10,
        fontWeight: '600',
    },

    // ── Modal Bomberos ──────────────────────────────────────────────────────────
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContent: {
        width: '100%',
        maxHeight: '70%',
        backgroundColor: '#1a1c23',
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: '#334155',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    modalTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '800',
    },
    modalScroll: {
        marginTop: 10,
    },
    modalEmpty: {
        color: '#94a3b8',
        textAlign: 'center',
        marginTop: 20,
        fontSize: 14,
    },
    responderItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#0f172a',
        padding: 12,
        borderRadius: 12,
        marginBottom: 10,
    },
    responderAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#3b82f6',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    responderInfo: {
        flex: 1,
    },
    responderName: {
        color: '#f8fafc',
        fontSize: 14,
        fontWeight: '700',
    },
    responderRole: {
        color: '#94a3b8',
        fontSize: 12,
        marginTop: 2,
    },
    responderStatusBadge: {
        backgroundColor: 'rgba(16,185,129,0.15)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
    },
    responderStatusText: {
        color: '#10b981',
        fontSize: 10,
        fontWeight: '800',
    },
    missionDetailsSection: {
        backgroundColor: '#0f172a',
        padding: 16,
        borderRadius: 12,
        marginBottom: 16,
        gap: 12,
    },
    missionDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    missionDetailTextContainer: {
        flex: 1,
    },
    missionDetailLabel: {
        fontSize: 10,
        fontWeight: '800',
        color: '#64748b',
        letterSpacing: 1,
    },
    missionDetailValue: {
        fontSize: 14,
        color: '#f8fafc',
        fontWeight: '600',
        marginTop: 2,
    },
    modalDivider: {
        height: 1,
        backgroundColor: '#334155',
        marginBottom: 16,
    },
    sectionSubtitle: {
        fontSize: 12,
        fontWeight: '800',
        color: '#94a3b8',
        letterSpacing: 1,
        marginBottom: 12,
    },
    returnButton: {
        backgroundColor: '#e11d48',
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 16,
    },
    returnButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '800',
        letterSpacing: 1,
    },
    // ── Estilos para el estado de Error ─────────────────────────────────────────
    errorBotonReintentar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#dc2626',
        paddingHorizontal: 24,
        height: 48,
        borderRadius: 8,
        marginTop: 24,
        gap: 8,
    },
    errorBotonTexto: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 1,
    },
});