import { StyleSheet, Platform } from 'react-native';

export const dataStyles = StyleSheet.create({
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 13,
        borderBottomWidth: 1,
        borderBottomColor: '#26282f',
        gap: 12,
    },
    iconBox: {
        width: 30,
        height: 30,
        borderRadius: 6,
        backgroundColor: '#26282f',
        alignItems: 'center',
        justifyContent: 'center',
    },
    textCol: { flex: 1 },
    label: {
        fontSize: 9,
        fontWeight: '800',
        color: '#475569',
        letterSpacing: 0.8,
        marginBottom: 2,
    },
    value: {
        fontSize: 14,
        fontWeight: '700',
        color: '#f8fafc',
    },
});

export const actionStyles = StyleSheet.create({
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#26282f',
        gap: 12,
    },
    iconBox: {
        width: 40,
        height: 40,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    textCol: { flex: 1 },
    title: {
        fontSize: 14,
        fontWeight: '700',
        color: '#f8fafc',
        marginBottom: 2,
    },
    sub: {
        fontSize: 11,
        color: '#64748b',
    },
});

// ── Styles ───────────────────────────────────────────────────────
export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#16181d',
    },

    // Top bar
    topBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingBottom: 16,
        backgroundColor: '#1a1c23',
        borderBottomWidth: 1,
        borderBottomColor: '#26282f',
    },
    topBarLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    topBarLogo: {
        width: 30,
        height: 30,
        borderRadius: 6,
        backgroundColor: '#2d1515',
        alignItems: 'center',
        justifyContent: 'center',
    },
    topBarTitle: {
        color: '#e11d48',
        fontSize: 16,
        fontWeight: '900',
        letterSpacing: 1,
    },
    topBarRight: { flexDirection: 'row', gap: 16, alignItems: 'center' },
    iconBtn: { padding: 4 },

    // Content
    scrollContent: { padding: 24 },

    pageLabel: {
        fontSize: 10,
        color: '#fca5a5',
        letterSpacing: 2,
        fontWeight: '700',
        marginBottom: 4,
    },
    pageTitle: {
        fontSize: 28,
        fontWeight: '900',
        color: '#f8fafc',
        letterSpacing: -1,
        lineHeight: 30,
        marginBottom: 24,
    },

    // Profile card
    profileCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1b1d24',
        borderRadius: 8,
        padding: 16,
        marginBottom: 12,
        gap: 14,
    },
    profileCardLeft: { position: 'relative' },
    avatarBox: {
        width: 68,
        height: 68,
        borderRadius: 8,
        backgroundColor: '#26282f',
        alignItems: 'center',
        justifyContent: 'center',
        borderLeftWidth: 3,
        borderLeftColor: '#dc2626',
    },
    onlineDot: {
        position: 'absolute',
        bottom: 3,
        right: 3,
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: '#22c55e',
        borderWidth: 2,
        borderColor: '#1b1d24',
    },
    profileCardInfo: { flex: 1 },
    profileName: {
        fontSize: 18,
        fontWeight: '900',
        color: '#f8fafc',
        marginBottom: 2,
    },
    profileUsername: {
        fontSize: 12,
        color: '#64748b',
        fontWeight: '600',
        marginBottom: 8,
    },
    badgesRow: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
    badge: {
        paddingHorizontal: 7,
        paddingVertical: 3,
        borderRadius: 4,
    },
    badgeText: {
        fontSize: 9,
        fontWeight: '800',
        letterSpacing: 0.4,
    },

    // Admin banner
    adminBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#1b1d24',
        borderLeftWidth: 3,
        borderLeftColor: '#dc2626',
        borderRadius: 6,
        padding: 14,
        marginBottom: 24,
    },
    adminBannerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    adminBannerTitle: { color: '#f8fafc', fontSize: 11, fontWeight: '900', letterSpacing: 0.6 },
    adminBannerSub: { color: '#64748b', fontSize: 11, marginTop: 1 },

    // Sections
    sectionTitle: {
        fontSize: 11,
        fontWeight: '700',
        color: '#94a3b8',
        letterSpacing: 1.2,
        marginBottom: 8,
        marginTop: 4,
    },
    card: {
        backgroundColor: '#1b1d24',
        borderRadius: 8,
        paddingHorizontal: 16,
        marginBottom: 20,
    },

    // Logout
    logoutBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 14,
        borderRadius: 6,
        backgroundColor: '#1b1d24',
        borderWidth: 1,
        borderColor: '#2d1515',
        marginBottom: 16,
        marginTop: 4,
    },
    logoutText: {
        color: '#e11d48',
        fontSize: 12,
        fontWeight: '900',
        letterSpacing: 1,
    },
    versionText: {
        textAlign: 'center',
        color: '#26282f',
        fontSize: 10,
        fontWeight: '700',
        letterSpacing: 1.5,
        marginBottom: 8,
    },

    // ── Edit Modal ───────────────────────────────────────────────
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'flex-end',
    },
    modalSheet: {
        backgroundColor: '#1a1c23',
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
        borderTopWidth: 1,
        borderColor: '#26282f',
        padding: 24,
        paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    },
    modalHandle: {
        width: 36,
        height: 4,
        borderRadius: 2,
        backgroundColor: '#26282f',
        alignSelf: 'center',
        marginBottom: 20,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 16,
    },
    modalIconBox: {
        width: 36,
        height: 36,
        borderRadius: 8,
        backgroundColor: '#2d1515',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalTitle: {
        flex: 1,
        fontSize: 13,
        fontWeight: '900',
        color: '#f8fafc',
        letterSpacing: 0.8,
    },
    modalClose: {
        width: 30,
        height: 30,
        borderRadius: 6,
        backgroundColor: '#26282f',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalDivider: { height: 1, backgroundColor: '#26282f', marginBottom: 16 },
    modalLabel: {
        fontSize: 9,
        fontWeight: '800',
        color: '#64748b',
        letterSpacing: 1,
        marginBottom: 8,
    },
    modalInputWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#26282f',
        borderRadius: 6,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: '#334155',
    },
    modalInput: {
        flex: 1,
        paddingVertical: 12,
        fontSize: 14,
        color: '#f8fafc',
        fontWeight: '600',
    },
    pwToggle: { padding: 4 },
    modalActions: { flexDirection: 'row', gap: 10, marginTop: 20 },
    modalCancelBtn: {
        flex: 1,
        paddingVertical: 13,
        borderRadius: 6,
        backgroundColor: '#26282f',
        borderWidth: 1,
        borderColor: '#334155',
        alignItems: 'center',
    },
    modalCancelText: { fontSize: 11, fontWeight: '900', color: '#64748b', letterSpacing: 1 },
    modalSaveBtn: {
        flex: 2,
        paddingVertical: 13,
        borderRadius: 6,
        backgroundColor: '#dc2626',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalSaveText: { fontSize: 11, fontWeight: '900', color: '#fff', letterSpacing: 1 },
    roleBreadcrumb: {
        height: 24,
        backgroundColor: '#1b1d24',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        borderLeftWidth: 3,
        borderBottomWidth: 1,
        borderBottomColor: '#26282f',
    },
    roleBreadcrumbDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        marginRight: 8,
    },
    roleBreadcrumbText: {
        fontSize: 9,
        fontWeight: '900',
        fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
        letterSpacing: 1.2,
    },
});